### ISSUE TITLE
Conversion rate calculation

### ISSUE THREAD

**Issue by Irfanwustl** [hqyone/BCR_Evaluator#1]
Thanks for the nice tool.

I am wondering how to calculate the conversion rate for a given sample. BCR_Evaluator outputs a string. Probably rc1, rc2, and rc3 are the unconverted rate. I am a little confused here. Should not be a one single number conversion rate here? How can we get conversion the rate from rc1, rc2, and rc3?

In addition, all my samples are paired-end fastq files. So should I input fastq1,fastq2 together and BCR_Evaluator output the rate for the sample? Or do I need to run them separately and then take the average of the output to get the conversion rate per sample?

**Comment by hqyone** [comment]
Hi Irfanwustl, you can get the conversion rate (CR) with this formula: CR = 1- Mean(rc1, rc2,  rc3).  In most of cases, these three values should be very close to each other.  More precisely, the rc1 represent the ApG unconverted ratio and the rc2 and rc3 represent the GpG unconverted ratio in telomeres.  For the second question, theoretically, both combining fastq1,fastq2 and taking the mean from them should works and generate very similar results. However, I prefer the second way.  Because you can compare the ratios from fastq1 and fastq2. If they are very different which may indicate some weird things happen.

**Comment by Irfanwustl** [comment]
Thanks  for the clear explanation. 

I am trying to run this tool in one of my FASTQ file, but keep getting error. 
The command I am using:

`python BCReval.py  -i FASTQ/a.fastq.gz -o a.fastq_cr.txt`

And the following index out of range error I am getting.

> Traceback (most recent call last):
  File "BCReval.py", line 341, in <module>
    main(sys.argv[1:])
  File "BCReval.py", line 326, in main
    rep = getTeloRepCount(min_rep_number, f)
  File "BCReval.py", line 166, in getTeloRepCount
    len_dic1[int(len(bs)/unit_len)]+=1
IndexError: list index out of range 

Will you please help?

**Comment by hqyone** [comment]
Please change the line 96 and 97 to len_dic0 = [0]*30 and len_dic1 = [0]*30, that should solve the issue. If not, please let me know.

**Comment by hqyone** [comment]
I also updated the code in Github, you can download and try it.

**Comment by Irfanwustl** [comment]
Thank you so much. It is working now. 

I am using -n = 10 (as in the publication you mentioned that after n=8 the result becomes stable). Is n=10 okay? Will it affect the runtime?

However, it shows errors in smaller Fastq files (sub-sample). Is it a bug? I attached the error screenshot and the small fastq file if you want to reproduce.

Thanks again for this very helpful tool.

<img width="433" alt="Screen Shot 2021-07-25 at 11 09 02 PM" src="https://user-images.githubusercontent.com/43051380/126931905-0dfc7333-4a0a-4ca3-ab1f-ff841a19f83b.png">

[a_R1_001.fastq.gz](https://github.com/hqyone/BCR_Evaluator/files/6875488/a_R1_001.fastq.gz)

**Comment by hqyone** [comment]
Hi Irfanwustl , the n=10 is more stringent than n=8 to define a telomeric read, but it may result in the loss of more reads.  So It is  a balance here. I think both 8 or 10 should be OK in most of cases. For the error, as the Fastq is too small, no telomeric reads were detected which results in c_strand_unit_num equals to 0 here. I just fixed the bug on Github, you can test.

**Comment by Irfanwustl** [comment]
Yes. The error is gone now. Thanks.
